### ISSUE TITLE
hi,my friend, would you like to share the gpu version of this code?

### ISSUE THREAD

**Issue by daima2017** [deepopo/CENALP#4]
hi,my friend, would you like to share the gpu version of this code?

**Comment by deepopo** [comment]
Sorry, we did not provide a gpu version. Since the embedding process is not an end2end model, in line with DeepWalk, Node2vec, etc., and suffers a high cost in sampling, which cannot easily be optimized by gpu. Exploiting gpu in training process might work but will not significantly improve the time cost of the whole process.
